version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - DOMAIN
    ports:
      - 80:80
    volumes:
      - ./conf/templates-initiate:/etc/nginx/templates
      - ./conf/letsencrypt:/etc/letsencrypt
      - ./conf/certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d *.${DOMAIN} -d ${DOMAIN}
             --preferred-challenges dns
    volumes:
      - ./conf/letsencrypt:/etc/letsencrypt
      - ./conf/certbot/data:/var/www/certbot
